### ISSUE TITLE
Still not able to test it

### ISSUE THREAD

**Issue by lukyluket** [tuhiproject/tuhi#103]
Actually I have updated the distro so that now I am 100% sure that the python 3.6 is correctly installed.

By following the instructions in the readme, I get everything cloned and installed by I get the following messages

luca_17@DellucoXT3:~/tuhi$ tuhi
Traceback (most recent call last):
  File "/home/luca_17/.local/bin/tuhi", line 11, in <module>
    load_entry_point('tuhi==0.1', 'console_scripts', 'tuhi')()
  File "/home/luca_17/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/luca_17/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/home/luca_17/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/home/luca_17/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/luca_17/.local/lib/python3.6/site-packages/tuhi-0.1-py3.6.egg/tuhi/base.py", line 19, in <module>
  File "/usr/local/lib/python3.6/dist-packages/gi-1.2-py3.6.egg/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(url)?

**Comment by whot** [comment]
this is inside `gi` again, something is still busted on your machine. Sorry, but this isn't a tuhi bug, this is well outside our package. Line 19 in tuhi/base.py is: `from gi.repository import GObject, GLib`

So you can probably reproduce that crash with an empty python script just containing that line.

**Comment by whot** [comment]
huh, looking at this again this turned out to be a completely different issue. the `gi` package is some old (dead) package that conflicts the namespace of the `gi.repository` and isn't python3 compatible. Please remove that package, PR #105 includes a patch so we don't drag this in anymore.
