### ISSUE TITLE
Running tuhi on a MacOS High Sierra

### ISSUE THREAD

**Issue by pbhogale** [tuhiproject/tuhi#110]
Having run into #108 on my ubuntu machine, I tried installing and running on a mac.

The installation was successful after installing pycairo with
`python3 -m pip install pycairo`.

however, running tuhi gives the following error 
```
/Users/uname/anaconda/lib/python3.6/site-packages/tuhi-0.1-py3.6.egg/tuhi/drawing.py:46: PyGIDeprecationWarning: GObject.property is deprecated; use GObject.Property instead
Traceback (most recent call last):
  File "/Users/uname/anaconda/bin/tuhi", line 11, in <module>
    load_entry_point('tuhi==0.1', 'console_scripts', 'tuhi')()
  File "/Users/uname/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/Users/uname/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/Users/uname/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2258, in load
  File "/Users/uname/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/uname/anaconda/lib/python3.6/site-packages/tuhi-0.1-py3.6.egg/tuhi/base.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/uname/anaconda/lib/python3.6/site-packages/tuhi-0.1-py3.6.egg/tuhi/wacom.py", line 141, in <module>
  File "/Users/uname/anaconda/lib/python3.6/site-packages/tuhi-0.1-py3.6.egg/tuhi/wacom.py", line 142, in WacomWrongModeException
AttributeError: module 'errno' has no attribute 'EBADE'
```

Python version info -
```
#> python3 --version
Python 3.6.1 :: Anaconda 4.4.0 (x86_64)
```

**Comment by whot** [comment]
urgh. tbh we don't really support macos mostly because we never thought about it. Wacom has their own applications here anyway and since they know the protocol they're likely going to be more stable.

Anyway, this would be fixable by just assigning ``errno.EBADE = 52`` during startup somewhere, if it's not in ``errno.errorcode.keys()``.

**Comment by theopoon** [comment]
I am here too for MacOS / Windows, Wacom did not release any software / drivers for the Bamboo Spark to work with a PC, only mobile app was released.

Contacted Wacom some time ago about desktop drivers / software, the official answer was there are none, and there is no plans for them to make one, they suggest user to use their Inkscape services.

So Tuhi project seems to be the only way of getting it to work with MacOS / Windows

**Comment by bentiss** [comment]
> I am here too for MacOS / Windows, Wacom did not release any software / drivers for the Bamboo Spark to work with a PC, only mobile app was released.
>
> Contacted Wacom some time ago about desktop drivers / software, the official answer was there are none, and there is no plans for them to make one, they suggest user to use their Inkscape services.

I am sorry to hear that, but the one thing that completely prevents us to port this project to Windows or MacOS is the bluetooth stack. On Linux, we have `bluez` which we use and which provides a dbus API. MacOS and Windows have their own stack which we do not know about at all.

> So Tuhi project seems to be the only way of getting it to work with MacOS / Windows

The thing you can get from this project is the protocol of the devices. But then, you will be on your own to re-write the tool. The other solution would be for someone to write a compatible layer between the proprietary bluetooth stack on these system and the dbus API we rely on. But I am not sure anybody has started such thing.
