### ISSUE TITLE
tuhi on Raspberry Pi 3

### ISSUE THREAD

**Issue by theopoon** [tuhiproject/tuhi#116]
Follow the instruction of installation, am having issue with

~/tuhi/tuhi
Traceback (most recent call last):
  File "/usr/local/bin/tuhi", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pygobject' distribution was not found and is required by tuhi

Tried and installed apt-get install python-gobject, no luck...

Any idea? thanks.

**Comment by bentiss** [comment]
> Tried and installed apt-get install python-gobject, no luck...

Maybe try python3-gobject?

**Comment by theopoon** [comment]
Nope, no such package.

Just notice Raspbian comes with Python 3.5 instead of 3.6, let me see how can I overcome this.

**Comment by bentiss** [comment]
> Just notice Raspbian comes with Python 3.5 instead of 3.6, let me see how can I overcome this.

This is going to be a blocker here :(

**Comment by whot** [comment]
Closing based on https://github.com/tuhiproject/tuhi/issues/116#issuecomment-457534764, we require python 3.6 (mostly for `f`-strings iirc, but even if we drop all those someone would have to do that work)
