### ISSUE TITLE
Dependency Required: svgwrite

### ISSUE THREAD

**Issue by ckilimci** [tuhiproject/tuhi#200]
Hi all,

After successful build, I got below error when I want to run:

$ ./builddir/tuhi.devel 
Running from source tree, using local files
Running from source tree, using local files
11:08:58 DEBUG: tuhi.dbus: Bus name aquired
11:08:58 DEBUG: tuhi.ble: Adapter: /org/bluez/hci0
Traceback (most recent call last):
  File "/home/caglar/Documents/tuhi/builddir/tuhi-gui.devel", line 67, in <module>
    from tuhi.gui.application import Application
  File "/home/caglar/Documents/tuhi/tuhi/gui/application.py", line 17, in <module>
    from .window import MainWindow
  File "/home/caglar/Documents/tuhi/tuhi/gui/window.py", line 17, in <module>
    from .drawingperspective import DrawingPerspective
  File "/home/caglar/Documents/tuhi/tuhi/gui/drawingperspective.py", line 15, in <module>
    from .drawing import Drawing
  File "/home/caglar/Documents/tuhi/tuhi/gui/drawing.py", line 21, in <module>
    from tuhi.svg import JsonSvg
  File "/home/caglar/Documents/tuhi/tuhi/svg.py", line 16, in <module>
    import svgwrite
ModuleNotFoundError: No module named 'svgwrite'

After installed python3-svgwrite package, I successfully run.

Sincerely,
Caglar

**Comment by whot** [comment]
Note to self, [meson's python module](https://mesonbuild.com/Python-module.html#find_installation) has a new `modules` kwarg that takes a list of required modules. But only on 0.51 and that's not even in F30 so we can't use that reliably yet.
