### ISSUE TITLE
live mode is broken in recent releases

### ISSUE THREAD

**Issue by bentiss** [tuhiproject/tuhi#206]
See #205 

The script can not start the tuhi server anymore:
```
> sudo ./tools/tuhi-live.py
dropping privileges
No-one is handling org.freedesktop.tuhi1, attempting to start a daemon
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "./tools/tuhi-live.py", line 61, in maybe_start_tuhi
    t = tuhi.base.Tuhi()
  File "/home/btissoir/Src/tuhi/tools/../tuhi/base.py", line 302, in __init__
    self.config = TuhiConfig()
  File "/home/btissoir/Src/tuhi/tools/../tuhi/config.py", line 40, in __new__
    Path(self._base_path).mkdir(parents=True, exist_ok=True)
  File "/usr/lib64/python3.7/pathlib.py", line 994, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib64/python3.7/pathlib.py", line 649, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib64/python3.7/pathlib.py", line 633, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

And the coordinates are off

**Comment by whot** [comment]
remaining issues seems to be that ctrl+c kills tuhi before `StopLive` can be sent to the tablet
