### ISSUE TITLE
Unable to build Tuhi with meson on ElemantaryOS Juno, despite python3 being installed

### ISSUE THREAD

**Issue by N07070** [tuhiproject/tuhi#226]
Hello,

I'm currently trying to build Tuhi following the instructions of the README.md. I'm using the current master branch.

I'm on elementaryOS Juno, which is up to date. 

When trying to build, this error is shown :

```
The Meson build system
Version: 0.49.2
Source dir: /home/user/Téléchargements/tuhi
Build dir: /home/user/Téléchargements/tuhi/builddir
Build type: native build
Project name: tuhi
Project version: 0.3
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Dependency python3 found: NO (tried pkgconfig)

meson.build:9:0: ERROR:  Dependency "python3" not found, tried pkgconfig

A full log can be found at /home/user/Téléchargements/tuhi/builddir/meson-logs/meson-log.txt
```

But, python3 is installed, as shown ;

```
user@bidule:~/Téléchargements/tuhi$ python3 -V
Python 3.6.8
```
How should I proceed from there ?

Thank you.

**Comment by whot** [comment]
you need `python3-devel` or whatever the development package is called. See https://github.com/tuhiproject/tuhi/blob/master/.circleci/config.yml#L10 for a list of of packages required

**Comment by N07070** [comment]
Hello,

I installed python3-devel, and all the depends. The installation has no issues, but when I try to launch the app, it fails. See the logs below ; 

```
$> ninja: Entering directory `builddir'
[0/1] Installing files.
Installing /home/user/Téléchargements/tuhi/builddir/po/pl.gmo to /usr/local/share/locale/pl/LC_MESSAGES/tuhi.mo
gtk-update-icon-cache: Cache file created successfully.
Installing subdir /home/user/Téléchargements/tuhi/tuhi to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/user/Téléchargements/tuhi/tuhi/wacom.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/user/Téléchargements/tuhi/tuhi/__init__.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/user/Téléchargements/tuhi/tuhi/dbusserver.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/user/Téléchargements/tuhi/tuhi/base.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/user/Téléchargements/tuhi/tuhi/config.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/user/Téléchargements/tuhi/tuhi/export.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/user/Téléchargements/tuhi/tuhi/drawing.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/user/Téléchargements/tuhi/tuhi/protocol.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/user/Téléchargements/tuhi/tuhi/util.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/user/Téléchargements/tuhi/tuhi/ble.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/user/Téléchargements/tuhi/tuhi/dbusclient.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/user/Téléchargements/tuhi/tuhi/uhid.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/user/Téléchargements/tuhi/tuhi/gui/__init__.py to /usr/local/lib/python3.6/site-packages/tuhi/gui
Installing /home/user/Téléchargements/tuhi/tuhi/gui/window.py to /usr/local/lib/python3.6/site-packages/tuhi/gui
Installing /home/user/Téléchargements/tuhi/tuhi/gui/config.py to /usr/local/lib/python3.6/site-packages/tuhi/gui
Installing /home/user/Téléchargements/tuhi/tuhi/gui/drawing.py to /usr/local/lib/python3.6/site-packages/tuhi/gui
Installing /home/user/Téléchargements/tuhi/tuhi/gui/README.md to /usr/local/lib/python3.6/site-packages/tuhi/gui
Installing /home/user/Téléchargements/tuhi/tuhi/gui/drawingperspective.py to /usr/local/lib/python3.6/site-packages/tuhi/gui
Installing /home/user/Téléchargements/tuhi/tuhi/gui/application.py to /usr/local/lib/python3.6/site-packages/tuhi/gui
Installing data/org.freedesktop.Tuhi.desktop to /usr/local/share/applications
Installing data/org.freedesktop.Tuhi.appdata.xml to /usr/local/share/metainfo
Installing data/tuhi.gresource to /usr/local/share/tuhi
Installing org.freedesktop.Tuhi.desktop to /usr/local/share/applications
Installing org.freedesktop.Tuhi.appdata.xml to /usr/local/share/metainfo
Installing /home/user/Téléchargements/tuhi/data/org.freedesktop.Tuhi.svg to /usr/local/share/icons/hicolor/scalable/apps
Installing /home/user/Téléchargements/tuhi/data/org.freedesktop.Tuhi-symbolic.svg to /usr/local/share/icons/hicolor/symbolic/apps
Installing /home/user/Téléchargements/tuhi/builddir/tuhi to /usr/local/bin
Installing /home/user/Téléchargements/tuhi/builddir/tuhi-gui to /usr/local/libexec/tuhi
Installing /home/user/Téléchargements/tuhi/builddir/tuhi-server to /usr/local/libexec/tuhi
Installing /home/user/Téléchargements/tuhi/data/org.freedesktop.Tuhi.svg to /usr/local/share/icons/hicolor
Running custom install script '/usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=tuhi'
Running custom install script '/usr/bin/env sh /home/user/Téléchargements/tuhi/meson_install.sh'
user@bidule:~/Téléchargements/tuhi$ tuhi
Traceback (most recent call last):
  File "/usr/local/libexec/tuhi/tuhi-server", line 14, in <module>
    import tuhi.base
ModuleNotFoundError: No module named 'tuhi'
Traceback (most recent call last):
  File "/usr/local/libexec/tuhi/tuhi-gui", line 31, in <module>
    from tuhi.gui.application import main
ModuleNotFoundError: No module named 'tuhi'
```

**Comment by whot** [comment]
looks like your default python installation doesn't include `/usr/local/` in its `PYTHONPATH`.
You can either build with `meson --prefix=/usr/` or figure out why `/usr/local` is missing. What's the output of 

```
python3 -c 'import sys; print(sys.path)'
```
