### ISSUE TITLE
No module found - need an help asap for the university

### ISSUE THREAD

**Issue by smartlady31** [tuhiproject/tuhi#250]
Hi everybody,
I need to use my wacom tablet for the lectures (on Ubuntu 18.04) and I have installed all the serial drivers needed and tuhi 0.3. However, when I call it from the terminal, the following happens:

> Traceback (most recent call last):
  File "/usr/local/libexec/tuhi/tuhi-server", line 14, in <module>
    import tuhi.base
ModuleNotFoundError: No module named 'tuhi'
Traceback (most recent call last):
  File "/usr/local/libexec/tuhi/tuhi-gui", line 31, in <module>
    from tuhi.gui.application import main
ModuleNotFoundError: No module named 'tuhi'
>

Could you please help me somehow? Thank you

**Comment by smartlady31** [comment]
Just in case someone will have the same problem:
I've just solved it via a link from libexec to the tuhi directory in Downloads tuhi-0.3.
Just a visibility issue.
