### ISSUE TITLE
Unexpected pen id packet header

### ISSUE THREAD

**Issue by colmode** [tuhiproject/tuhi#256]
Linux Mint 20 Ulyana
Wacom Intuos Pro Paper Edition - Medium PTH660P

On trying to sync any drawing
```
tuhi.protocol.StrokeParsingError: Unexpected pen id packet header: 191. data: bf fa c3 0d e4 15 5f 11    ff
```

Full(er) log:
```
14:58:43 DEBUG: tuhi: E0:9F:2A:A1:FC:DA: UUID 04630697d2ec protocol: intuos_pro
14:58:43 DEBUG: tuhi.ble.E0:9F:2A:A1:FC:DA: Connecting
14:58:43 DEBUG: tuhi: E0:9F:2A:A1:FC:DA: UUID 04630697d2ec protocol: intuos_pro
14:58:43 DEBUG: tuhi.ble.E0:9F:2A:A1:FC:DA: Connecting
14:58:43 DEBUG: tuhi.ble.E0:9F:2A:A1:FC:DA: Already connecting
14:58:43 DEBUG: tuhi.ble.E0:9F:2A:A1:FC:DA: Connection established
14:58:45 DEBUG: tuhi.fw: sessionid: 913407ed6ce3417d919b7134a611d930-2
14:58:45 DEBUG: tuhi: E0:9F:2A:A1:FC:DA: connected for DeviceMode.LISTEN
14:58:45 DEBUG: tuhi.wacom: E0:9F:2A:A1:FC:DA: starting for mode LISTEN
14:58:45 DEBUG: tuhi.fw: command: CONNECT
14:58:45 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: TX NORDIC --> e6 / 06 / 04 63 06 97 d2 ec
14:58:46 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: RX NORDIC <-- 50 06 04 63 06 97 d2 ec
14:58:46 DEBUG: tuhi.fw: command: SET_TIME
14:58:46 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: TX NORDIC --> b6 / 06 / 66 e9 15 5f 00 00
14:58:46 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: RX NORDIC <-- b3 01 00
14:58:46 DEBUG: tuhi.fw: command: GET_BATTERY
14:58:46 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: TX NORDIC --> b9 / 01 / 00
14:58:46 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: RX NORDIC <-- ba 02 3e 00
14:58:46 INFO: tuhi.wacom: device battery: 62% (discharging)
14:58:46 DEBUG: tuhi.fw: command: GET_WIDTH
14:58:46 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: TX NORDIC --> ea / 02 / 03 00
14:58:46 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: RX NORDIC <-- eb 06 03 00 00 af 00 00
14:58:46 DEBUG: tuhi.fw: command: GET_HEIGHT
14:58:46 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: TX NORDIC --> ea / 02 / 04 00
14:58:46 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: RX NORDIC <-- eb 06 04 00 a0 73 00 00
14:58:46 DEBUG: tuhi.fw: command: GET_POINT_SIZE
14:58:46 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: TX NORDIC --> ea / 02 / 14 00
14:58:46 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: RX NORDIC <-- eb 06 14 00 06 00 00 00
14:58:46 INFO: tuhi.wacom: dimensions: 44800x29600, point size 5µm
14:58:46 DEBUG: tuhi.fw: command: GET_FIRMWARE
14:58:46 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: TX NORDIC --> b7 / 01 / 00
14:58:46 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: RX NORDIC <-- b8 09 00 42 31 38 30 31    33 31 61
14:58:46 DEBUG: tuhi.fw: command: GET_FIRMWARE
14:58:46 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: TX NORDIC --> b7 / 01 / 01
14:58:47 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: RX NORDIC <-- b8 09 01 43 33 32 35 2e    30 30 33
14:58:47 INFO: tuhi.wacom: firmware is B180131a-C325.003
14:58:47 DEBUG: tuhi.fw: command: SET_FILE_TRANSFER_REPORTING_TYPE
14:58:47 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: TX NORDIC --> ec / 06 / 06 00 00 00 00 00
14:58:47 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: RX NORDIC <-- b3 01 00
14:58:47 DEBUG: tuhi.fw: command: SET_MODE
14:58:47 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: TX NORDIC --> b1 / 01 / 01
14:58:47 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: RX NORDIC <-- b3 01 00
14:58:47 DEBUG: tuhi.fw: command: SET_MODE
14:58:47 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: TX NORDIC --> b1 / 01 / 01
14:58:47 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: RX NORDIC <-- b3 01 00
14:58:47 DEBUG: tuhi.fw: command: AVAILABLE_FILES_COUNT
14:58:47 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: TX NORDIC --> c1 / 01 / 00
14:58:47 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: RX NORDIC <-- c2 02 03 00
14:58:47 DEBUG: tuhi.wacom: Drawings available: 3
14:58:47 DEBUG: tuhi.fw: command: GET_STROKES
14:58:47 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: TX NORDIC --> cc / 01 / 00
14:58:47 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: RX NORDIC <-- cf 0a 7c 0d 00 00 1a e4    15 5f 00 00
14:58:47 INFO: tuhi.wacom: receiving 3452 bytes drawn on UTC 200720183610
14:58:47 DEBUG: tuhi.fw: command: DOWNLOAD_OLDEST_FILE
14:58:47 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: TX NORDIC --> c3 / 01 / 00
14:58:47 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: RX NORDIC <-- c8 0b be 70 0d 00 00 1a    e4 15 5f 00 00
14:58:47 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: RX PEN <-- 67 82 69 65 1a e4 15 5f    00 00 03 00 00 00 00 00    bf fa c3 0d
14:58:47 DEBUG: tuhi.fw: E0:9F:2A:A1:FC:DA: RX PEN <-- e4 15 5f 11 ff 18 2e 99    80 28 42 00 10 ff ff ff    2f 8b 97 6a
...
fd03a8fa020fa8fcf909a8fbf657a8faf669a8fcfa97a8fb02e5a8ff06fda8020ab2a8010378a8050ab2a8060bd3a80509fea80409c6a80506e8880309a803020fa806ff06a80a020fa80f0727a8190a27a81d1157a8211482e81c0f180fe80b074b0ae8f2fe8701fcffffffffffff'
14:58:48 DEBUG: tuhi.protocol: FileHeader: time: 200720183610, stroke count: 3
14:58:48 DEBUG: tuhi.protocol: Next data packet STROKE_HEADER: bf fa c3 0d e4 15 5f 11    ff 18 2e 99 80 28 42 00 …
14:58:48 DEBUG: tuhi.ble.E0:9F:2A:A1:FC:DA: Disconnecting
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/libexec/tuhi/tuhi/wacom.py", line 978, in _run
    self._wacom_protocol.retrieve_data()
  File "/usr/local/libexec/tuhi/tuhi/wacom.py", line 779, in retrieve_data
    if not self.read_offline_data():
  File "/usr/local/libexec/tuhi/tuhi/wacom.py", line 650, in read_offline_data
    drawing = self.parse_pen_data(pen_data, timestamp)
  File "/usr/local/libexec/tuhi/tuhi/wacom.py", line 622, in parse_pen_data
    f = StrokeFile(data)
  File "/usr/local/libexec/tuhi/tuhi/protocol.py", line 1478, in __init__
    self.bytesize += self._parse_data(data[offset:])
  File "/usr/local/libexec/tuhi/tuhi/protocol.py", line 1551, in _parse_data
    packet = StrokeHeader(data)
  File "/usr/local/libexec/tuhi/tuhi/protocol.py", line 1725, in __init__
    self._parse_intuos_pro(data, header, payload)
  File "/usr/local/libexec/tuhi/tuhi/protocol.py", line 1763, in _parse_intuos_pro
    raise StrokeParsingError(f'Unexpected pen id packet header: {header}.', data[:9])
tuhi.protocol.StrokeParsingError: Unexpected pen id packet header: 191. data: bf fa c3 0d e4 15 5f 11    ff
14:58:51 DEBUG: tuhi.ble.E0:9F:2A:A1:FC:DA: Disconnected
14:58:51 DEBUG: tuhi: E0:9F:2A:A1:FC:DA: disconnected
```

**Comment by colmode** [comment]
[tuhi-20-07-20-14:55:52.log](https://github.com/tuhiproject/tuhi/files/5011575/tuhi-20-07-20-14.55.52.log)

[bluetooth-log.tar.gz](https://github.com/tuhiproject/tuhi/files/5011577/bluetooth-log.tar.gz)

**Comment by whot** [comment]
Can you check if this is the same as #283 please?
