### ISSUE TITLE
Install Error xdg Module Not Found

### ISSUE THREAD

**Issue by Aflynn50** [tuhiproject/tuhi#268]
I'm trying to install tuhi on ubuntu 20.04 for my new Bamboo Slate. Initially I tried installing as described in the readme but running the tuhi command threw an error so I install the deb package from the ppa [here](https://launchpad.net/~leo.robol/+archive/ubuntu/tuhi) and now have version (0.5-7~focal) installed. The package installs with no problem but upon running the tuhi command I get the error below
```
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/tuhi/tuhi-server", line 14, in <module>
    import tuhi.base
  File "/usr/lib/python3.8/dist-packages/tuhi/base.py", line 19, in <module>
    import xdg.BaseDirectory
ModuleNotFoundError: No module named 'xdg.BaseDirectory'
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/tuhi/tuhi-gui", line 31, in <module>
    from tuhi.gui.application import main
  File "/usr/lib/python3.8/dist-packages/tuhi/gui/application.py", line 14, in <module>
    from .window import MainWindow
  File "/usr/lib/python3.8/dist-packages/tuhi/gui/window.py", line 14, in <module>
    from .drawingperspective import DrawingPerspective
  File "/usr/lib/python3.8/dist-packages/tuhi/gui/drawingperspective.py", line 14, in <module>
    from .drawing import Drawing
  File "/usr/lib/python3.8/dist-packages/tuhi/gui/drawing.py", line 16, in <module>
    import xdg.BaseDirectory
ModuleNotFoundError: No module named 'xdg.BaseDirectory'
```
It would appear that I do not have xdg installed however as far as I can tell I do:

```
$ pip3 install xdg
Requirement already satisfied: xdg in ./.local/lib/python3.8/site-packages (5.0.1)
$ pip3 install pyxdg
Requirement already satisfied: pyxdg in /usr/lib/python3/dist-packages (0.26)
```
I've checked that the module is on the python path and all seems to be in order yet tuhi is not finding it. Does anyone know what the problem could be?
Thanks, Alastair

**Comment by Aflynn50** [comment]
Ah, I fixed it, I needed to set my PYTHONPATH env variable to include the locations of xdg.
