### ISSUE TITLE
Traceback while trying to register new device

### ISSUE THREAD

**Issue by jave** [tuhiproject/tuhi#269]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/joakim/tuhi/tuhi/wacom.py", line 974, in _run
    self.register_device()
  File "/home/joakim/tuhi/tuhi/wacom.py", line 949, in register_device
    protocol = wp.register_device(self._uuid)
  File "/home/joakim/tuhi/tuhi/wacom.py", line 373, in register_device
    protocol_version = self.p.execute(Interactions.REGISTER_WAIT_FOR_BUTTON).protocol_version
  File "/home/joakim/tuhi/tuhi/protocol.py", line 285, in execute
    return self.get(key, *args, **kwargs).execute()
  File "/home/joakim/tuhi/tuhi/protocol.py", line 553, in execute
    raise MissingReplyError(self.request)
tuhi.protocol.MissingReplyError: <exception str() failed>

**Comment by jave** [comment]
I was trying to register a new device in tuhi, and it wasnt going very well.

After I got the traceback above, I read the stdout trace more carefully and noticed a "press the button now" and was faster in pressing the button, and now i managed to connect the device.

so maybe the instructions in the register window can be made a bit clearer, like stdout?
