### ISSUE TITLE
ModuleNotFoundError: No module named 'tuhi'

### ISSUE THREAD

**Issue by manumart** [tuhiproject/tuhi#298]
After installing all the dependencies, and Tuhi without problem on Ubuntu 22.04 (and Python 3.10.6)  I get the following error message (just bellow).

Any help welcomed!  

Best regards

~$ tuhi
Traceback (most recent call last):
  File "/usr/local/libexec/tuhi/tuhi-server", line 14, in <module>
    import tuhi.base
ModuleNotFoundError: No module named 'tuhi'
Traceback (most recent call last):
  File "/usr/local/libexec/tuhi/tuhi-gui", line 31, in <module>
    from tuhi.gui.application import main
ModuleNotFoundError: No module named 'tuhi'

**Comment by whot** [comment]
only time for a quick answer: looks like you installed into `/usr/local` and the tuhi package likely into `/usr/local/lib/site-packages/...`. This is probably not in your `PYTHONPATH`. Can be fixed by supplying `--prefix=/usr` to meson or adjusting the `PYTHONPATH` manually. Both should be easy to find in your preferred search engine.

**Comment by MathieuDR** [comment]
Hello @manumart I'm having the same issue and am not proficient with python. My module seems to be installed into `/usr/local/lib/python3/dist-packages` as I have a `tuhi` directory there.

My `PYTHONPATH` seems to include this: `> python -c "import sys; print(sys.path)": ['', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/***/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages']
`
