### ISSUE TITLE
dbus

### ISSUE THREAD

**Issue by jacolamanna** [tuhiproject/tuhi#301]
Tuhi crashes as it does not find dbus process on mac osx (dbus installed and launched using brew)
same problem when running tuhi-server directly or the version in the sources tuhi-devel etc...

11:20:21 ERROR: tuhi.dbus: Bus not available, is there another Tuhi process running?
Traceback (most recent call last):
  File "/Users/jaco/.pyenv/versions/3.9.18/lib/python3.9/site-packages/tuhi/gui/application.py", line 64, in do_activate
    window = MainWindow(application=self)
  File "/Users/jaco/.pyenv/versions/3.9.18/lib/python3.9/site-packages/tuhi/gui/window.py", line 105, in __init__
    self._tuhi = TuhiDBusClientManager()
  File "/Users/jaco/.pyenv/versions/3.9.18/lib/python3.9/site-packages/tuhi/dbusclient.py", line 321, in __init__
    super().__init__(TUHI_DBUS_NAME, ORG_FREEDESKTOP_TUHI1_MANAGER, ROOT_PATH)
  File "/Users/jaco/.pyenv/versions/3.9.18/lib/python3.9/site-packages/tuhi/dbusclient.py", line 45, in __init__
    self._connect_to_session()
  File "/Users/jaco/.pyenv/versions/3.9.18/lib/python3.9/site-packages/tuhi/dbusclient.py", line 97, in _connect_to_session
    raise e
  File "/Users/jaco/.pyenv/versions/3.9.18/lib/python3.9/site-packages/tuhi/dbusclient.py", line 91, in _connect_to_session
    _DBusObject._connection = Gio.bus_get_sync(Gio.BusType.SESSION, None)
gi.repository.GLib.GError: g-spawn-exit-error-quark: Error spawning command line “dbus-launch --autolaunch=b4bbc0c5a632e5eb1aa1eaa5656f58ec --binary-syntax --close-stderr”: Child process exited with code 1 (1)

Thanks for any help

**Comment by whot** [comment]
Honestly - no idea, tuhi has never been tested on macos so if it works that's mostly by coincidence rather than intention.

**Comment by jacolamanna** [comment]
Uh thanks for your fast reply. Too bad, I'd love to use it on a mac. Actually I would mostly need the live connection to a specific slate device, do you have any suggestion for doing it more straight (no gui, no dbus interface...)?

**Comment by whot** [comment]
honestly, no idea on a mac. we communicate with bluez via dbus so you can't really get around this here. Realistically you'd probably have to re-implement most of the protocol in a non-dbus way specifici to how macos does bluetooth.
